Fix integ helm values, deploymentConfig template (#246)
* Fix integ helm values, custom aspsp csv, no custom logback config [skip ci]

Causes an error during installation

Error: render error in "xs2a-adapter/templates/xs2a-adapter/deployment.yaml": template: xs2a-adapter/templates/xs2a-adapter/deployment.yaml:17:26: executing "xs2a-adapter/templates/xs2a-adapter/deployment.yaml" at <include (print $.Tem...>: error calling include: template: xs2a-adapter/templates/xs2a-adapter/configmap.yaml:10:28: executing "xs2a-adapter/templates/xs2a-adapter/configmap.yaml" at <.Values.logback.file>: invalid value; expected string

* Fix logging-config volume declaration on wrong conditional [skip ci]

Fails to deploy after helm upgrade due to not found configmap