Fix empty response body causes an exception (#408)
java.io.UncheckedIOException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected

Co-authored-by: Artem Snisarenko <asn@adorsys.com.ua>